# Monolithic Baseline — Bedrock Development Evaluation

This presentation notebook evaluates one tool-using Strands agent with Amazon Nova Lite. AMZN is the development batch and GOOGL is the validation batch. Gold answers are used only after inference.

## Setup

Load the reusable runtime and evaluation code from `src/`.

In [1]:
import sys
import warnings
from pathlib import Path
warnings.filterwarnings("ignore", message="IProgress not found.*")
project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(project_root / "src"))

In [2]:
from agent.data import load_question
from agent.monolithic import MonolithicAgentHarness
from agent.observation import format_observable_timeline, format_run_summary
from agent.tools import ProjectTools

In [3]:
from agent.data import load_gold_questions
from pandas import DataFrame
from evaluation.metrics import (
    evaluate_saved_results,
    format_evaluation_summary,
    save_evaluation_results, save_run_records,
)

In [4]:
from config import (
    BEDROCK_NOVA_LITE_MODEL_ID, NOVA_LITE_INPUT_USD_PER_MILLION_TOKENS,
    NOVA_LITE_OUTPUT_USD_PER_MILLION_TOKENS,
)

## Development benchmark

Load the frozen AMZN questions. Gold answers remain separate from agent inputs and appear only in answer comparisons.

In [5]:
ticker = "AMZN"
gold_records = load_gold_questions(ticker)
gold_by_id = {record["question_id"]: record for record in gold_records}

In [6]:
DataFrame([
    {"question_id": record["question_id"], "category": record["category"]}
    for record in gold_records
])

   question_id           category
0      amzn-01  direct_extraction
1      amzn-02  direct_extraction
2      amzn-03  direct_extraction
3      amzn-04  direct_extraction
4      amzn-05     single_formula
5      amzn-06     single_formula
6      amzn-07     single_formula
7      amzn-08     single_formula
8      amzn-09  period_comparison
9      amzn-10  period_comparison
10     amzn-11  period_comparison
11     amzn-12  period_comparison
12     amzn-13         multi_step
13     amzn-14         multi_step
14     amzn-15         multi_step
15     amzn-16         multi_step

## Preflight

Confirm that Bedrock, Langfuse, and the local Qdrant filing index are available before spending model calls.

In [7]:
harness = MonolithicAgentHarness(
    provider="bedrock", model_id=BEDROCK_NOVA_LITE_MODEL_ID
)
preflight = harness.preflight()

In [8]:
preflight

{'ready': True,
 'provider': 'bedrock',
 'model': 'amazon.nova-lite-v1:0',
 'reasoning_mode': 'none',
 'langfuse': 'authenticated',
 'qdrant_collection': 'sec_filing_chunks_v1'}

## Deterministic tool smoke check

Check fact evidence and Decimal arithmetic before asking the model to use them.

In [9]:
tools = ProjectTools()
facts = tools.lookup_fact(company="AMZN", concept="revenue")

In [10]:
facts

{'status': 'ok',
 'facts': [{'company': 'Amazon.com, Inc.',
   'ticker': 'AMZN',
   'concept': 'revenue',
   'evidence_id': 'fact-amzn-revenue-fy2023',
   'value': '574785000000',
   'unit': 'USD',
   'period': 'FY2023'},
  {'company': 'Amazon.com, Inc.',
   'ticker': 'AMZN',
   'concept': 'revenue',
   'evidence_id': 'fact-amzn-revenue-fy2024',
   'value': '637959000000',
   'unit': 'USD',
   'period': 'FY2024'},
  {'company': 'Amazon.com, Inc.',
   'ticker': 'AMZN',
   'concept': 'revenue',
   'evidence_id': 'fact-amzn-revenue-fy2025',
   'value': '716924000000',
   'unit': 'USD',
   'period': 'FY2025'}]}

In [11]:
calculation = tools.calculate(operation="percentage", inputs=["25", "200"])

In [12]:
calculation

{'status': 'ok', 'result': '12.5'}

## Question 1: direct extraction

Run one question, then inspect its complete audit trail before continuing.

In [13]:
question_1 = load_question("amzn-01")
gold_1 = gold_by_id[question_1.question_id]["answer"]
run_1 = harness.run_question(question_1.question)

In [14]:
run_1.answer

MonolithicAnswer(answer_text="Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.", values=[AnswerValue(label='consolidated net sales', value='716924000000', unit='USD', period='FY2025', source_evidence_ids=['fact-amzn-revenue-fy2025'])], evidence_ids=['fact-amzn-revenue-fy2025'], calculations=[], conclusions=["Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000."])

### Full trace: Question 1

In [15]:
print(format_observable_timeline(run_1.observable_timeline))

===== 01 SYSTEM PROMPT =====

You are a read-only SEC filing research agent. Use only the
supplied tools and frozen local data. Do not use outside knowledge, modify data, or
give financial advice, investment recommendations, predictions, or trade guidance.

- Use evidence only for the company in the question. Match its requested period and
  unit; before calculating, confirm every input has the requested period. Do not
  guess when evidence is missing or ambiguous.
- Prefer lookup_fact for normalized facts. Use search_filing when the requested
  concept, granularity, or context is not available through lookup_fact.
- Use calculate for every arithmetic step. For growth, calculate (new - old) / old
  * 100, not new / old * 100. Keep every used calculator operation, exact inputs,
  and exact result in calculations. Ensure directional wording agrees with results.
- Ground each reported value in returned evidence or a calculator result. Cite only
  returned evidence IDs that directly support that value; calculated values cite
  their input evidence. Put only final requested values in values, and put factual
  answer claims in conclusions. If the evidence cannot support an answer, say so.
- Structured values use an absolute plain decimal without commas or symbols, unit
  USD or percent, and periods such as FY2025 or FY2024 to FY2025. In answer_text,
  render USD as $1,000,000 without million/billion abbreviations. Round final
  percentages to two decimal places unless the user requests different precision;
  retain full precision in calculations and use the same rounded value in prose.

Return only the requested structured output. Keep the answer concise and do not
include hidden reasoning.


===== 02 TOOL DEFINITIONS =====

- search_filing: Search the frozen 10-K for relevant evidence.
- lookup_fact: Look up all normalized Company Facts observations for one concept.
- calculate: Perform one allowed deterministic Decimal calculation.

===== 03 USER INPUT =====

USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?

===== 04 MODEL CALL 1 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?

MODEL OUTPUT:
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')

TOKEN USAGE: inputTokens=1828, outputTokens=66, totalTokens=1894

===== 05 TOOL CALL =====

TOOL CALL: lookup_fact(concept='revenue', company='AMZN')

===== 06 TOOL RESULT =====

TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)

===== 07 MODEL CALL 2 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Values:
- consolidated net sales | 716924000000 | USD | FY2025 | sources: fact-amzn-revenue-fy2025
Evidence: fact-amzn-revenue-fy2025
Conclusions: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.

TOKEN USAGE: inputTokens=2148, outputTokens=213, totalTokens=2361

===== 08 TOOL CALL =====

STRUCTURED ANSWER:
Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Values:
- consolidated net sales | 716924000000 | USD | FY2025 | sources: fact-amzn-revenue-fy2025
Evidence: fact-amzn-revenue-fy2025
Conclusions: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.

===== 09 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned error

===== 10 MODEL CALL 3 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
ASSISTANT: STRUCTURED ANSWER:
Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Values:
- consolidated net sales | 716924000000 | USD | FY2025 | sources: fact-amzn-revenue-fy2025
Evidence: fact-amzn-revenue-fy2025
Conclusions: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
TOOL RESULT: MonolithicAnswer returned error

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Values:
- consolidated net sales | 716924000000 | USD | FY2025 | sources: fact-amzn-revenue-fy2025
Evidence: fact-amzn-revenue-fy2025
Conclusions: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.

TOKEN USAGE: inputTokens=2409, outputTokens=220, totalTokens=2629

===== 11 TOOL CALL =====

STRUCTURED ANSWER:
Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Values:
- consolidated net sales | 716924000000 | USD | FY2025 | sources: fact-amzn-revenue-fy2025
Evidence: fact-amzn-revenue-fy2025
Conclusions: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.

===== 12 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned success

### Run summary: Question 1

In [16]:
print(format_run_summary(run_1, gold_1))

Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?
Model answer: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Gold answer: 716924000000
Gold values: -
Tools: lookup_fact (ok)
Evidence: fact-amzn-revenue-fy2025
Latency: 5896.53 ms | Tokens: {'inputTokens': 6385, 'outputTokens': 499, 'totalTokens': 6884} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.0003831', 'output': '0.00011976', 'total': '0.00050286'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/f11900b8613feaa5e1ac852a5175871c

### Cost breakdown: Question 1

Nova Lite on-demand text pricing in `us-east-1`, frozen on 2026-08-24.

In [17]:
input_cost = run_1.token_usage["inputTokens"] * NOVA_LITE_INPUT_USD_PER_MILLION_TOKENS / 1_000_000
output_cost = run_1.token_usage["outputTokens"] * NOVA_LITE_OUTPUT_USD_PER_MILLION_TOKENS / 1_000_000
input_cost + output_cost

Decimal('0.00050286')

## Question 2: single formula

Run one formula question, then inspect it before moving on.

In [18]:
question_2 = load_question("amzn-05")
gold_2 = gold_by_id[question_2.question_id]["answer"]
run_2 = harness.run_question(question_2.question)

### Full trace: Question 2

In [19]:
print(format_observable_timeline(run_2.observable_timeline))

===== 01 SYSTEM PROMPT =====

You are a read-only SEC filing research agent. Use only the
supplied tools and frozen local data. Do not use outside knowledge, modify data, or
give financial advice, investment recommendations, predictions, or trade guidance.

- Use evidence only for the company in the question. Match its requested period and
  unit; before calculating, confirm every input has the requested period. Do not
  guess when evidence is missing or ambiguous.
- Prefer lookup_fact for normalized facts. Use search_filing when the requested
  concept, granularity, or context is not available through lookup_fact.
- Use calculate for every arithmetic step. For growth, calculate (new - old) / old
  * 100, not new / old * 100. Keep every used calculator operation, exact inputs,
  and exact result in calculations. Ensure directional wording agrees with results.
- Ground each reported value in returned evidence or a calculator result. Cite only
  returned evidence IDs that directly support that value; calculated values cite
  their input evidence. Put only final requested values in values, and put factual
  answer claims in conclusions. If the evidence cannot support an answer, say so.
- Structured values use an absolute plain decimal without commas or symbols, unit
  USD or percent, and periods such as FY2025 or FY2024 to FY2025. In answer_text,
  render USD as $1,000,000 without million/billion abbreviations. Round final
  percentages to two decimal places unless the user requests different precision;
  retain full precision in calculations and use the same rounded value in prose.

Return only the requested structured output. Keep the answer concise and do not
include hidden reasoning.


===== 02 TOOL DEFINITIONS =====

- search_filing: Search the frozen 10-K for relevant evidence.
- lookup_fact: Look up all normalized Company Facts observations for one concept.
- calculate: Perform one allowed deterministic Decimal calculation.

===== 03 USER INPUT =====

USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?

===== 04 MODEL CALL 1 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?

MODEL OUTPUT:
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')

TOKEN USAGE: inputTokens=1827, outputTokens=87, totalTokens=1914

===== 05 TOOL CALL =====

TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')

===== 06 TOOL CALL =====

TOOL CALL: lookup_fact(concept='revenue', company='AMZN')

===== 07 TOOL RESULT =====

TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)

===== 08 MODEL CALL 2 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)

MODEL OUTPUT:
ASSISTANT: TOOL CALL: calculate(inputs='79975000000', '716924000000', operation='percentage')

TOKEN USAGE: inputTokens=2420, outputTokens=74, totalTokens=2494

===== 09 TOOL CALL =====

TOOL CALL: calculate(inputs='79975000000', '716924000000', operation='percentage')

===== 10 TOOL RESULT =====

TOOL RESULT: calculate = 11.15529679575519859845674018

===== 11 MODEL CALL 3 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
ASSISTANT: TOOL CALL: calculate(inputs='79975000000', '716924000000', operation='percentage')
TOOL RESULT: calculate = 11.15529679575519859845674018

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
Amazon.com, Inc.'s operating margin in fiscal 2025 was 11.16 percent.
Values:
- operating margin | 11.16 | percent | FY2025 | sources: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Evidence: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Conclusions: -

TOKEN USAGE: inputTokens=2558, outputTokens=252, totalTokens=2810

===== 12 TOOL CALL =====

STRUCTURED ANSWER:
Amazon.com, Inc.'s operating margin in fiscal 2025 was 11.16 percent.
Values:
- operating margin | 11.16 | percent | FY2025 | sources: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Evidence: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Conclusions: -

===== 13 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned success

### Run summary: Question 2

In [20]:
print(format_run_summary(run_2, gold_2))

Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?
Model answer: Amazon.com, Inc.'s operating margin in fiscal 2025 was 11.16 percent.
Gold answer: 11.16
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Latency: 3814.25 ms | Tokens: {'inputTokens': 6805, 'outputTokens': 413, 'totalTokens': 7218} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0004083', 'output': '0.00009912', 'total': '0.00050742'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/fd92272effe7219390e92b6274ac67f0

## Question 3: period comparison

This example combines filing search, normalized facts, and calculations.

In [21]:
question_3 = load_question("amzn-12")
gold_3 = gold_by_id[question_3.question_id]["answer"]
run_3 = harness.run_question(question_3.question)

### Full trace: Question 3

In [22]:
print(format_observable_timeline(run_3.observable_timeline))

===== 01 SYSTEM PROMPT =====

You are a read-only SEC filing research agent. Use only the
supplied tools and frozen local data. Do not use outside knowledge, modify data, or
give financial advice, investment recommendations, predictions, or trade guidance.

- Use evidence only for the company in the question. Match its requested period and
  unit; before calculating, confirm every input has the requested period. Do not
  guess when evidence is missing or ambiguous.
- Prefer lookup_fact for normalized facts. Use search_filing when the requested
  concept, granularity, or context is not available through lookup_fact.
- Use calculate for every arithmetic step. For growth, calculate (new - old) / old
  * 100, not new / old * 100. Keep every used calculator operation, exact inputs,
  and exact result in calculations. Ensure directional wording agrees with results.
- Ground each reported value in returned evidence or a calculator result. Cite only
  returned evidence IDs that directly support that value; calculated values cite
  their input evidence. Put only final requested values in values, and put factual
  answer claims in conclusions. If the evidence cannot support an answer, say so.
- Structured values use an absolute plain decimal without commas or symbols, unit
  USD or percent, and periods such as FY2025 or FY2024 to FY2025. In answer_text,
  render USD as $1,000,000 without million/billion abbreviations. Round final
  percentages to two decimal places unless the user requests different precision;
  retain full precision in calculations and use the same rounded value in prose.

Return only the requested structured output. Keep the answer concise and do not
include hidden reasoning.


===== 02 TOOL DEFINITIONS =====

- search_filing: Search the frozen 10-K for relevant evidence.
- lookup_fact: Look up all normalized Company Facts observations for one concept.
- calculate: Perform one allowed deterministic Decimal calculation.

===== 03 USER INPUT =====

USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?

===== 04 MODEL CALL 1 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?

MODEL OUTPUT:
ASSISTANT: TOOL CALL: search_filing(query='AWS operating income', company='AMZN')
ASSISTANT: TOOL CALL: search_filing(query='consolidated operating income', company='AMZN')

TOKEN USAGE: inputTokens=1838, outputTokens=95, totalTokens=1933

===== 05 TOOL CALL =====

TOOL CALL: search_filing(query='AWS operating income', company='AMZN')

===== 06 TOOL CALL =====

TOOL CALL: search_filing(query='consolidated operating income', company='AMZN')

===== 07 TOOL RESULT =====

TOOL RESULT: search_filing completed; ranked records are saved locally.
TOOL RESULT: search_filing completed; ranked records are saved locally.

===== 08 MODEL CALL 2 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?
ASSISTANT: TOOL CALL: search_filing(query='AWS operating income', company='AMZN')
ASSISTANT: TOOL CALL: search_filing(query='consolidated operating income', company='AMZN')
TOOL RESULT: search_filing completed; ranked records are saved locally.
TOOL RESULT: search_filing completed; ranked records are saved locally.

MODEL OUTPUT:
ASSISTANT: TOOL CALL: calculate(inputs='29619', '24967', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='79975', '68593', operation='percentage')

TOKEN USAGE: inputTokens=12786, outputTokens=103, totalTokens=12889

===== 09 TOOL CALL =====

TOOL CALL: calculate(inputs='29619', '24967', operation='percentage')

===== 10 TOOL CALL =====

TOOL CALL: calculate(inputs='79975', '68593', operation='percentage')

===== 11 TOOL RESULT =====

TOOL RESULT: calculate = 118.6325950254335723154564025
TOOL RESULT: calculate = 116.593529952035922032860496

===== 12 MODEL CALL 3 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?
ASSISTANT: TOOL CALL: search_filing(query='AWS operating income', company='AMZN')
ASSISTANT: TOOL CALL: search_filing(query='consolidated operating income', company='AMZN')
TOOL RESULT: search_filing completed; ranked records are saved locally.
TOOL RESULT: search_filing completed; ranked records are saved locally.
ASSISTANT: TOOL CALL: calculate(inputs='29619', '24967', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='79975', '68593', operation='percentage')
TOOL RESULT: calculate = 118.6325950254335723154564025
TOOL RESULT: calculate = 116.593529952035922032860496

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
From fiscal 2024 to fiscal 2025, AWS operating income grew by 118.63% while Amazon's consolidated operating income grew by 116.59%.
Values:
- AWS operating income growth | 118.63 | percent | FY2024 to FY2025 | sources: filing-amzn-2025-page-0068-table-01
- Amazon consolidated operating income growth | 116.59 | percent | FY2024 to FY2025 | sources: filing-amzn-2025-page-0068-table-01
Evidence: filing-amzn-2025-page-0068-table-01
Conclusions: From fiscal 2024 to fiscal 2025, AWS operating income grew by 118.63% while Amazon's consolidated operating income grew by 116.59%.

TOKEN USAGE: inputTokens=13004, outputTokens=437, totalTokens=13441

===== 13 TOOL CALL =====

STRUCTURED ANSWER:
From fiscal 2024 to fiscal 2025, AWS operating income grew by 118.63% while Amazon's consolidated operating income grew by 116.59%.
Values:
- AWS operating income growth | 118.63 | percent | FY2024 to FY2025 | sources: filing-amzn-2025-page-0068-table-01
- Amazon consolidated operating income growth | 116.59 | percent | FY2024 to FY2025 | sources: filing-amzn-2025-page-0068-table-01
Evidence: filing-amzn-2025-page-0068-table-01
Conclusions: From fiscal 2024 to fiscal 2025, AWS operating income grew by 118.63% while Amazon's consolidated operating income grew by 116.59%.

===== 14 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned success

### Run summary: Question 3

In [23]:
print(format_run_summary(run_3, gold_3))

Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?
Model answer: From fiscal 2024 to fiscal 2025, AWS operating income grew by 118.63% while Amazon's consolidated operating income grew by 116.59%.
Gold answer: consolidated operating income grew faster than AWS operating income; the growth-rate difference was 2.10 percentage points
Gold values: AWS operating income growth: 14.49 percent, consolidated operating income growth: 16.59 percent
Tools: search_filing (ok), search_filing (ok), calculate (ok), calculate (ok)
Evidence: filing-amzn-2025-page-0068-table-01
Latency: 8803.83 ms | Tokens: {'inputTokens': 27628, 'outputTokens': 635, 'totalTokens': 28263} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00165768', 'output': '0.0001524', 'total': '0.00181008'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/2d823b2acdbce0ee3b7de9757f82d5db

## Question 4: multi-step calculation

The final dry run checks a longer chain before the complete batch.

In [24]:
question_4 = load_question("amzn-16")
gold_4 = gold_by_id[question_4.question_id]["answer"]
run_4 = harness.run_question(question_4.question)

### Full trace: Question 4

In [25]:
print(format_observable_timeline(run_4.observable_timeline))

===== 01 SYSTEM PROMPT =====

You are a read-only SEC filing research agent. Use only the
supplied tools and frozen local data. Do not use outside knowledge, modify data, or
give financial advice, investment recommendations, predictions, or trade guidance.

- Use evidence only for the company in the question. Match its requested period and
  unit; before calculating, confirm every input has the requested period. Do not
  guess when evidence is missing or ambiguous.
- Prefer lookup_fact for normalized facts. Use search_filing when the requested
  concept, granularity, or context is not available through lookup_fact.
- Use calculate for every arithmetic step. For growth, calculate (new - old) / old
  * 100, not new / old * 100. Keep every used calculator operation, exact inputs,
  and exact result in calculations. Ensure directional wording agrees with results.
- Ground each reported value in returned evidence or a calculator result. Cite only
  returned evidence IDs that directly support that value; calculated values cite
  their input evidence. Put only final requested values in values, and put factual
  answer claims in conclusions. If the evidence cannot support an answer, say so.
- Structured values use an absolute plain decimal without commas or symbols, unit
  USD or percent, and periods such as FY2025 or FY2024 to FY2025. In answer_text,
  render USD as $1,000,000 without million/billion abbreviations. Round final
  percentages to two decimal places unless the user requests different precision;
  retain full precision in calculations and use the same rounded value in prose.

Return only the requested structured output. Keep the answer concise and do not
include hidden reasoning.


===== 02 TOOL DEFINITIONS =====

- search_filing: Search the frozen 10-K for relevant evidence.
- lookup_fact: Look up all normalized Company Facts observations for one concept.
- calculate: Perform one allowed deterministic Decimal calculation.

===== 03 USER INPUT =====

USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?

===== 04 MODEL CALL 1 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?

MODEL OUTPUT:
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_cash_flow', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='total_assets', company='AMZN')

TOKEN USAGE: inputTokens=1843, outputTokens=134, totalTokens=1977

===== 05 TOOL CALL =====

TOOL CALL: lookup_fact(concept='revenue', company='AMZN')

===== 06 TOOL CALL =====

TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')

===== 07 TOOL CALL =====

TOOL CALL: lookup_fact(concept='operating_cash_flow', company='AMZN')

===== 08 TOOL CALL =====

TOOL CALL: lookup_fact(concept='total_assets', company='AMZN')

===== 09 TOOL RESULT =====

TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 84946000000 USD (fact-amzn-operating-cash-flow-fy2023)
- FY2024: 115877000000 USD (fact-amzn-operating-cash-flow-fy2024)
- FY2025: 139514000000 USD (fact-amzn-operating-cash-flow-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 527854000000 USD (fact-amzn-total-assets-fy2023)
- FY2024: 624894000000 USD (fact-amzn-total-assets-fy2024)
- FY2025: 818042000000 USD (fact-amzn-total-assets-fy2025)

===== 10 MODEL CALL 2 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_cash_flow', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='total_assets', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 84946000000 USD (fact-amzn-operating-cash-flow-fy2023)
- FY2024: 115877000000 USD (fact-amzn-operating-cash-flow-fy2024)
- FY2025: 139514000000 USD (fact-amzn-operating-cash-flow-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 527854000000 USD (fact-amzn-total-assets-fy2023)
- FY2024: 624894000000 USD (fact-amzn-total-assets-fy2024)
- FY2025: 818042000000 USD (fact-amzn-total-assets-fy2025)

MODEL OUTPUT:
ASSISTANT: TOOL CALL: calculate(inputs='68593000000', '637959000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='79975000000', '68593000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='115877000000', '84946000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='139514000000', '115877000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='624894000000', '527854000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='818042000000', '624894000000', operation='percentage')

TOKEN USAGE: inputTokens=3004, outputTokens=279, totalTokens=3283

===== 11 TOOL CALL =====

TOOL CALL: calculate(inputs='68593000000', '637959000000', operation='percentage')

===== 12 TOOL CALL =====

TOOL CALL: calculate(inputs='79975000000', '68593000000', operation='percentage')

===== 13 TOOL CALL =====

TOOL CALL: calculate(inputs='115877000000', '84946000000', operation='percentage')

===== 14 TOOL CALL =====

TOOL CALL: calculate(inputs='139514000000', '115877000000', operation='percentage')

===== 15 TOOL CALL =====

TOOL CALL: calculate(inputs='624894000000', '527854000000', operation='percentage')

===== 16 TOOL CALL =====

TOOL CALL: calculate(inputs='818042000000', '624894000000', operation='percentage')

===== 17 TOOL RESULT =====

TOOL RESULT: calculate = 10.75194487420037964822190768
TOOL RESULT: calculate = 116.593529952035922032860496
TOOL RESULT: calculate = 136.412544439997174675676312
TOOL RESULT: calculate = 120.398353426478075890815261
TOOL RESULT: calculate = 118.3838712977452098496932864
TOOL RESULT: calculate = 130.9089221531971822421082616

===== 18 MODEL CALL 3 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_cash_flow', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='total_assets', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 84946000000 USD (fact-amzn-operating-cash-flow-fy2023)
- FY2024: 115877000000 USD (fact-amzn-operating-cash-flow-fy2024)
- FY2025: 139514000000 USD (fact-amzn-operating-cash-flow-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 527854000000 USD (fact-amzn-total-assets-fy2023)
- FY2024: 624894000000 USD (fact-amzn-total-assets-fy2024)
- FY2025: 818042000000 USD (fact-amzn-total-assets-fy2025)
ASSISTANT: TOOL CALL: calculate(inputs='68593000000', '637959000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='79975000000', '68593000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='115877000000', '84946000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='139514000000', '115877000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='624894000000', '527854000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='818042000000', '624894000000', operation='percentage')
TOOL RESULT: calculate = 10.75194487420037964822190768
TOOL RESULT: calculate = 116.593529952035922032860496
TOOL RESULT: calculate = 136.412544439997174675676312
TOOL RESULT: calculate = 120.398353426478075890815261
TOOL RESULT: calculate = 118.3838712977452098496932864
TOOL RESULT: calculate = 130.9089221531971822421082616

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Values:
- Net Sales Growth | 10.75 | percent | FY2024 to FY2025 | sources: -
- Operating Income Growth | 116.59 | percent | FY2024 to FY2025 | sources: -
- Operating Cash Flow Growth | 136.41 | percent | FY2024 to FY2025 | sources: -
- Total Assets Growth | 130.91 | percent | FY2024 to FY2025 | sources: -
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Conclusions: -

TOKEN USAGE: inputTokens=3604, outputTokens=804, totalTokens=4408

===== 19 TOOL CALL =====

STRUCTURED ANSWER:
Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Values:
- Net Sales Growth | 10.75 | percent | FY2024 to FY2025 | sources: -
- Operating Income Growth | 116.59 | percent | FY2024 to FY2025 | sources: -
- Operating Cash Flow Growth | 136.41 | percent | FY2024 to FY2025 | sources: -
- Total Assets Growth | 130.91 | percent | FY2024 to FY2025 | sources: -
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Conclusions: -

===== 20 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned error

===== 21 MODEL CALL 4 =====

MODEL INPUT:
USER: Company: Amazon.com, Inc.
Ticker: AMZN
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
ASSISTANT: TOOL CALL: lookup_fact(concept='revenue', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_income', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='operating_cash_flow', company='AMZN')
ASSISTANT: TOOL CALL: lookup_fact(concept='total_assets', company='AMZN')
TOOL RESULT: lookup_fact
- FY2023: 574785000000 USD (fact-amzn-revenue-fy2023)
- FY2024: 637959000000 USD (fact-amzn-revenue-fy2024)
- FY2025: 716924000000 USD (fact-amzn-revenue-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 36852000000 USD (fact-amzn-operating-income-fy2023)
- FY2024: 68593000000 USD (fact-amzn-operating-income-fy2024)
- FY2025: 79975000000 USD (fact-amzn-operating-income-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 84946000000 USD (fact-amzn-operating-cash-flow-fy2023)
- FY2024: 115877000000 USD (fact-amzn-operating-cash-flow-fy2024)
- FY2025: 139514000000 USD (fact-amzn-operating-cash-flow-fy2025)
TOOL RESULT: lookup_fact
- FY2023: 527854000000 USD (fact-amzn-total-assets-fy2023)
- FY2024: 624894000000 USD (fact-amzn-total-assets-fy2024)
- FY2025: 818042000000 USD (fact-amzn-total-assets-fy2025)
ASSISTANT: TOOL CALL: calculate(inputs='68593000000', '637959000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='79975000000', '68593000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='115877000000', '84946000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='139514000000', '115877000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='624894000000', '527854000000', operation='percentage')
ASSISTANT: TOOL CALL: calculate(inputs='818042000000', '624894000000', operation='percentage')
TOOL RESULT: calculate = 10.75194487420037964822190768
TOOL RESULT: calculate = 116.593529952035922032860496
TOOL RESULT: calculate = 136.412544439997174675676312
TOOL RESULT: calculate = 120.398353426478075890815261
TOOL RESULT: calculate = 118.3838712977452098496932864
TOOL RESULT: calculate = 130.9089221531971822421082616
ASSISTANT: STRUCTURED ANSWER:
Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Values:
- Net Sales Growth | 10.75 | percent | FY2024 to FY2025 | sources: -
- Operating Income Growth | 116.59 | percent | FY2024 to FY2025 | sources: -
- Operating Cash Flow Growth | 136.41 | percent | FY2024 to FY2025 | sources: -
- Total Assets Growth | 130.91 | percent | FY2024 to FY2025 | sources: -
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Conclusions: -
TOOL RESULT: MonolithicAnswer returned error

MODEL OUTPUT:
ASSISTANT: STRUCTURED ANSWER:
Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Values:
- Net Sales Growth | 10.75 | percent | FY2024 to FY2025 | sources: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025
- Operating Income Growth | 116.59 | percent | FY2024 to FY2025 | sources: fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025
- Operating Cash Flow Growth | 136.41 | percent | FY2024 to FY2025 | sources: fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025
- Total Assets Growth | 130.91 | percent | FY2024 to FY2025 | sources: fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Conclusions: -

TOKEN USAGE: inputTokens=4526, outputTokens=958, totalTokens=5484

===== 22 TOOL CALL =====

STRUCTURED ANSWER:
Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Values:
- Net Sales Growth | 10.75 | percent | FY2024 to FY2025 | sources: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025
- Operating Income Growth | 116.59 | percent | FY2024 to FY2025 | sources: fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025
- Operating Cash Flow Growth | 136.41 | percent | FY2024 to FY2025 | sources: fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025
- Total Assets Growth | 130.91 | percent | FY2024 to FY2025 | sources: fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Conclusions: -

===== 23 TOOL RESULT =====

TOOL RESULT: MonolithicAnswer returned success

### Run summary: Question 4

In [26]:
print(format_run_summary(run_4, gold_4))

Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
Model answer: Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Gold answer: all four measures increased; total assets grew fastest; net sales grew slowest; the spread between the fastest and slowest growth rates was 18.53 percentage points
Gold values: net sales growth: 12.38 percent, operating income growth: 16.59 percent, operating cash flow growth: 20.40 percent, total assets growth: 30.91 percent
Tools: lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Latency: 14554.14 ms | Tokens: {'inputTokens': 12977, 'outputTokens': 2175, 'totalTokens': 15152} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.00077862', 'output': '0.000522', 'total': '0.00130062'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/638c65e3cdd1bd1e7253e23e47548f5a

## Full AMZN development batch

Run all 16 development questions with Nova Lite. Each attempt is appended to the official local JSONL run log.

In [27]:
batch_runs = harness.run_batch(ticker)
assert [run.question.question_id for run in batch_runs] == [gold["question_id"] for gold in gold_records]
results_dir = save_run_records(batch_runs)

In [28]:
DataFrame([
    {"question_id": run.question.question_id, "status": run.status}
    for run in batch_runs
])

   question_id   status
0      amzn-01  success
1      amzn-02  success
2      amzn-03  success
3      amzn-04  success
4      amzn-05  success
5      amzn-06  success
6      amzn-07  success
7      amzn-08  success
8      amzn-09  success
9      amzn-10  success
10     amzn-11  success
11     amzn-12  success
12     amzn-13  success
13     amzn-14  success
14     amzn-15  success
15     amzn-16  success

## Inspect every answer

The compact view makes incorrect values, missing evidence, failed calls, and unexpectedly expensive questions visible before looking at aggregate scores.

In [29]:
for run in batch_runs:
    gold = gold_by_id[run.question.question_id]["answer"]
    print(format_run_summary(run, gold))
    print("-" * 88)

Question: What was Amazon.com, Inc.'s consolidated net sales in fiscal 2025?
Model answer: Amazon.com, Inc.'s consolidated net sales in fiscal 2025 was $716,924,000,000.
Gold answer: 716924000000
Gold values: -
Tools: lookup_fact (ok)
Evidence: fact-amzn-revenue-fy2025
Latency: 2749.09 ms | Tokens: {'inputTokens': 3971, 'outputTokens': 238, 'totalTokens': 4209} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00023826', 'output': '0.00005712', 'total': '0.00029538'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/2ea26114406a173cdf2105df20e06f61
----------------------------------------------------------------------------------------
Question: What was Amazon.com, Inc.'s consolidated operating income in fiscal 2025?
Model answer: Amazon.com, Inc.'s consolidated operating income in fiscal 2025 was $79,975,000,000.
Gold answer: 79975000000
Gold values: -
Tools: lookup_fact (ok)
Evidence: fact-amzn-operating-income-fy2025
Latency: 2308.71 ms | Tokens: {'inputTokens': 3984, 'outputTokens': 243, 'totalTokens': 4227} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00023904', 'output': '0.00005832', 'total': '0.00029736'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/7fce8c0ba2b71da3f88998bb2e06794e
----------------------------------------------------------------------------------------
Question: Which Amazon reportable segment generated the most operating income in fiscal 2025, and how much did it generate?
Model answer: The AWS segment generated the most operating income in fiscal 2025, with an amount of $45,606 million.
Gold answer: 45606000000
Gold values: -
Tools: search_filing (ok), calculate (ok), calculate (ok)
Evidence: filing-amzn-2025-page-0068-table-01, filing-amzn-2025-page-0027-table-01
Latency: 4514.83 ms | Tokens: {'inputTokens': 15368, 'outputTokens': 456, 'totalTokens': 15824} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00092208', 'output': '0.00010944', 'total': '0.00103152'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/ce380ed82fe5ce844416ab61b9cb538a
----------------------------------------------------------------------------------------
Question: What was Amazon's International segment operating income in fiscal 2025?
Model answer: Amazon's International segment operating income in fiscal 2025 was $4,750 million.
Gold answer: 4750000000
Gold values: -
Tools: search_filing (ok)
Evidence: filing-amzn-2025-page-0068-table-01, filing-amzn-2025-page-0027-table-01
Latency: 4819.46 ms | Tokens: {'inputTokens': 13772, 'outputTokens': 553, 'totalTokens': 14325} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.00082632', 'output': '0.00013272', 'total': '0.00095904'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/be4f7469e423776eb432c9a76b9d1f7d
----------------------------------------------------------------------------------------
Question: What was Amazon.com, Inc.'s operating margin in fiscal 2025?
Model answer: Amazon.com, Inc.'s operating margin in fiscal 2025 was 11.16 percent.
Gold answer: 11.16
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2025
Latency: 3821.77 ms | Tokens: {'inputTokens': 6799, 'outputTokens': 413, 'totalTokens': 7212} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00040794', 'output': '0.00009912', 'total': '0.00050706'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/30c64ce92a3d53fe3a1fce783f7533b5
----------------------------------------------------------------------------------------
Question: What was Amazon.com, Inc.'s net profit margin in fiscal 2025?
Model answer: Amazon.com, Inc.'s net profit margin in fiscal 2025 was 10.83%
Gold answer: 10.83
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-net-income-fy2025, fact-amzn-revenue-fy2025
Latency: 4810.72 ms | Tokens: {'inputTokens': 6908, 'outputTokens': 537, 'totalTokens': 7445} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041448', 'output': '0.00012888', 'total': '0.00054336'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/602efd2ba4790ac0f14fdc9767463c4e
----------------------------------------------------------------------------------------
Question: What share of Amazon.com, Inc.'s fiscal 2025 net sales was represented by operating cash flow?
Model answer: The share of Amazon.com, Inc.'s fiscal 2025 net sales represented by operating cash flow was 19.46 percent.
Gold answer: 19.46
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-amzn-revenue-fy2025, fact-amzn-operating-cash-flow-fy2025
Latency: 4748.66 ms | Tokens: {'inputTokens': 6865, 'outputTokens': 454, 'totalTokens': 7319} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0004119', 'output': '0.00010896', 'total': '0.00052086'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/4af3dbc7a96952cf8851779c2cf2b60e
----------------------------------------------------------------------------------------
Question: What was Amazon.com, Inc.'s operating cash flow as a percentage of net income in fiscal 2025?
Model answer: Amazon.com, Inc.'s operating cash flow as a percentage of net income in fiscal 2025 was 179.62%
Gold answer: 179.62
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-amzn-operating-cash-flow-fy2025, fact-amzn-net-income-fy2025
Latency: 4093.89 ms | Tokens: {'inputTokens': 6914, 'outputTokens': 473, 'totalTokens': 7387} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041484', 'output': '0.00011352', 'total': '0.00052836'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/7ed40bbbe030a525cefb2fddffab8eab
----------------------------------------------------------------------------------------
Question: Between fiscal 2024 and fiscal 2025, how did Amazon's net sales growth compare with its operating income growth?
Model answer: Between fiscal 2024 and fiscal 2025, Amazon's net sales growth was 88.99% and its operating income growth was 15.77%. Net sales growth was higher than operating income growth.
Gold answer: operating income grew faster than net sales; the growth-rate difference was 4.22 percentage points
Gold values: net sales growth: 12.38 percent, operating income growth: 16.59 percent
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025
Latency: 5207.39 ms | Tokens: {'inputTokens': 6964, 'outputTokens': 691, 'totalTokens': 7655} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041784', 'output': '0.00016584', 'total': '0.00058368'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/5e896e57ff2aea02c289c69e3b5d808b
----------------------------------------------------------------------------------------
Question: How did Amazon's net income growth compare with its operating cash flow growth from fiscal 2024 to fiscal 2025?
Model answer: Amazon's net income growth from fiscal 2024 to fiscal 2025 was 76.28%, while its operating cash flow growth was 83.06%. Operating cash flow growth was higher than net income growth.
Gold answer: net income grew faster than operating cash flow; the growth-rate difference was 10.69 percentage points
Gold values: net income growth: 31.09 percent, operating cash flow growth: 20.40 percent
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-net-income-fy2024, fact-amzn-net-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025
Latency: 5240.72 ms | Tokens: {'inputTokens': 6992, 'outputTokens': 692, 'totalTokens': 7684} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041952', 'output': '0.00016608', 'total': '0.00058560'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/054cc368be611d33ca1faab0d296121d
----------------------------------------------------------------------------------------
Question: How did Amazon.com, Inc.'s total assets change from fiscal 2024 to fiscal 2025 in dollar and percentage terms?
Model answer: Amazon.com, Inc.'s total assets increased by $97,040,000,000 from fiscal 2024 to fiscal 2025, representing a 30.91% increase.
Gold answer: total assets increased
Gold values: absolute change: 193148000000 USD, percentage change: 30.91 percent
Tools: lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Latency: 4796.43 ms | Tokens: {'inputTokens': 6416, 'outputTokens': 618, 'totalTokens': 7034} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00038496', 'output': '0.00014832', 'total': '0.00053328'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/e4c718fbe8567801ee4d1cee0a3137d9
----------------------------------------------------------------------------------------
Question: From fiscal 2024 to fiscal 2025, how did AWS operating income growth compare with Amazon's consolidated operating income growth?
Model answer: From fiscal 2024 to fiscal 2025, AWS operating income grew by 11.9% while Amazon's consolidated operating income grew by 16.6%.
Gold answer: consolidated operating income grew faster than AWS operating income; the growth-rate difference was 2.10 percentage points
Gold values: AWS operating income growth: 14.49 percent, consolidated operating income growth: 16.59 percent
Tools: search_filing (ok), search_filing (ok), calculate (ok), calculate (ok)
Evidence: filing-amzn-2025-page-0068-table-01
Latency: 6619.41 ms | Tokens: {'inputTokens': 27628, 'outputTokens': 622, 'totalTokens': 28250} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00165768', 'output': '0.00014928', 'total': '0.00180696'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/4ee228d7bb32c2aa633bf031beec4d85
----------------------------------------------------------------------------------------
Question: Between fiscal 2024 and fiscal 2025, how did Amazon's operating margin and net profit margin develop, and which changed more?
Model answer: Between fiscal 2024 and fiscal 2025, Amazon's net profit margin changed more than its operating margin.
Gold answer: operating margin increased by 0.40 percentage points; net profit margin increased by 1.55 percentage points; net profit margin changed more
Gold values: 2024 operating margin: 10.75 percent, 2025 operating margin: 11.16 percent, 2024 net profit margin: 9.29 percent, 2025 net profit margin: 10.83 percent
Tools: lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok), calculate (failed), calculate (ok), calculate (ok), calculate (failed), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-net-income-fy2024, fact-amzn-net-income-fy2025
Latency: 14987.13 ms | Tokens: {'inputTokens': 19227, 'outputTokens': 1949, 'totalTokens': 21176} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00115362', 'output': '0.00046776', 'total': '0.00162138'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/b8fe0a8fbe2b65ecd2f34babee2b8bb0
----------------------------------------------------------------------------------------
Question: How did AWS's share of Amazon's consolidated operating income change from fiscal 2024 to fiscal 2025?
Model answer: AWS's share of Amazon's consolidated operating income increased by 3.39% from fiscal 2024 to fiscal 2025.
Gold answer: AWS's share of consolidated operating income declined by 1.05 percentage points
Gold values: 2024 AWS share of consolidated operating income: 58.07 percent, 2025 AWS share of consolidated operating income: 57.03 percent
Tools: search_filing (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: filing-amzn-2025-page-0068-table-01
Latency: 6560.89 ms | Tokens: {'inputTokens': 16077, 'outputTokens': 680, 'totalTokens': 16757} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00096462', 'output': '0.0001632', 'total': '0.00112782'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/eb83a05d20ccb2d70465f952910942ab
----------------------------------------------------------------------------------------
Question: How did Amazon's fiscal 2025 operating cash flow compare with its average annual operating cash flow for fiscal 2023 through fiscal 2025?
Model answer: Amazon's fiscal 2025 operating cash flow was 178.48% higher than its average annual operating cash flow for fiscal 2023 through fiscal 2025.
Gold answer: fiscal 2025 operating cash flow was 22.98 percent above the three-year average
Gold values: three-year average operating cash flow: 113445666666.67 USD, 2025 difference from average: 26068333333.33 USD, 2025 percentage difference from average: 22.98 percent
Tools: lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-operating-cash-flow-fy2023, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025
Latency: 7000.18 ms | Tokens: {'inputTokens': 9321, 'outputTokens': 906, 'totalTokens': 10227} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00055926', 'output': '0.00021744', 'total': '0.00077670'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/d7d547bdb811564a58fafa4f91dcc25a
----------------------------------------------------------------------------------------
Question: Did Amazon's net sales, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
Model answer: Amazon's net sales, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Gold answer: all four measures increased; total assets grew fastest; net sales grew slowest; the spread between the fastest and slowest growth rates was 18.53 percentage points
Gold values: net sales growth: 12.38 percent, operating income growth: 16.59 percent, operating cash flow growth: 20.40 percent, total assets growth: 30.91 percent
Tools: lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-amzn-revenue-fy2024, fact-amzn-revenue-fy2025, fact-amzn-operating-income-fy2024, fact-amzn-operating-income-fy2025, fact-amzn-operating-cash-flow-fy2024, fact-amzn-operating-cash-flow-fy2025, fact-amzn-total-assets-fy2024, fact-amzn-total-assets-fy2025
Latency: 13864.35 ms | Tokens: {'inputTokens': 15976, 'outputTokens': 1887, 'totalTokens': 17863} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.00095856', 'output': '0.00045288', 'total': '0.00141144'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/fc46d6d253ab907bce9b21d18b6cd1ab
----------------------------------------------------------------------------------------

## Deterministic evaluation

Gold values, calculation steps, required tools, and saved tool events are compared with ordinary Python. Structured final values must match the gold number and unit exactly, and extra final values fail. Formatting is scored separately across the structured values and answer text.

Retrieval is measured from saved tool events. Haiku 4.5 optionally adds qualitative 1–5 workflow scores without overriding deterministic numerical correctness.

In [30]:
saved_evaluation = evaluate_saved_results(
    latest=True, architecture=batch_runs[0].architecture, ticker=ticker,
)
assert saved_evaluation["results_directory"] == results_dir
question_metrics = saved_evaluation["question_rows"]
retrieval_metrics = saved_evaluation["retrieval_rows"]
summary = saved_evaluation["summary"]

## Exploratory Haiku 4.5 workflow review

These qualitative scores support diagnosis only. They cannot override deterministic numerical or audit failures.

In [31]:
saved_evaluation = evaluate_saved_results(
    latest=True, rerun_judge=True,
    architecture=batch_runs[0].architecture, ticker=ticker,
)
assert saved_evaluation["results_directory"] == results_dir
judge_metrics = saved_evaluation["judge_rows"] or []
summary = saved_evaluation["summary"]

In [32]:
DataFrame(judge_metrics, columns=(
    "question_id", "llm_answer_correctness_grade", "workflow_correctness",
    "chronological_coherence", "workflow_efficiency", "auditability",
))

,question_id,llm_answer_correctness_grade,workflow_correctness,chronological_coherence,workflow_efficiency,auditability
0,amzn-01,5,5,5,5,5
1,amzn-02,5,5,5,5,5
2,amzn-03,4,4,5,3,3
3,amzn-04,2,2,5,5,4
4,amzn-05,5,5,5,5,5
5,amzn-06,5,5,5,5,5
6,amzn-07,5,5,5,5,5
7,amzn-08,5,5,5,5,5
8,amzn-09,1,1,2,3,4
9,amzn-10,1,1,4,3,4
10,amzn-11,2,1,2,2,4
11,amzn-12,1,2,2,3,2
12,amzn-13,2,4,5,5,4
13,amzn-14,1,1,2,2,2
14,amzn-15,1,1,2,2,5
15,amzn-16,2,2,5,4,3

### AMZN questions needing review

Only runs with a failed deterministic check appear here.

In [33]:
CHECKS = ("numerical_correct", "evidence_valid", "evidence_complete",
          "value_evidence_valid", "periods_valid", "formatting_correct",
          "audit_trail_complete")
failed_question_metrics = [row for row in question_metrics if row["status"] != "success"
                           or any(row[name] is not True for name in CHECKS)]
DataFrame(failed_question_metrics, columns=(
    "question_id", "category", "numerical_correct",
    "evidence_complete", "formula_correct", "formatting_correct",
    "audit_trail_complete",
))

,question_id,category,numerical_correct,evidence_complete,formula_correct,formatting_correct,audit_trail_complete
0,amzn-03,direct_extraction,False,True,None,False,False
1,amzn-04,direct_extraction,False,True,None,False,False
2,amzn-09,period_comparison,False,True,False,True,False
3,amzn-10,period_comparison,False,True,False,True,False
4,amzn-11,period_comparison,False,True,False,True,False
5,amzn-12,period_comparison,False,True,False,False,False
6,amzn-13,multi_step,False,True,False,False,False
7,amzn-14,multi_step,False,True,False,True,False
8,amzn-15,multi_step,False,True,False,True,False
9,amzn-16,multi_step,False,True,False,False,False

### Metrics by question type

Category scores show whether errors are concentrated in extraction, one formula, comparisons, or longer calculation chains.

In [34]:
DataFrame(summary["by_category"]).T.rename_axis("question_type")

,run_count,numerical_correctness_rate,evidence_completeness_rate,formula_correctness_rate,formatting_correctness_rate
question_type,,,,,
direct_extraction,4.0,0.5,1.0,NaN,0.50
multi_step,4.0,0.0,1.0,0.0,0.50
period_comparison,4.0,0.0,1.0,0.0,0.75
single_formula,4.0,1.0,1.0,1.0,1.00

### Final metrics

Higher is better except for unsupported-number rate and irrelevant retrieval rate. Evidence validity checks whether cited IDs were returned; evidence completeness checks whether every final value cites returned source evidence. Retrieval scores each search call's top five independently.

In [35]:
print(format_evaluation_summary(summary))

Runs: 16
run_success_rate: 100.00%
numerical_correctness_rate: 37.50%
evidence_validity_rate: 100.00%
evidence_completeness_rate: 100.00%
formula_correctness_rate: 33.33%
formatting_correctness_rate: 68.75%
unsupported_number_rate: 37.50%
audit_trail_completeness_rate: 37.50%
math_repair_invocation_rate: 0.00%
math_repair_success_rate: 0.00%
tool_precision: 96.55%
tool_recall: 93.33%
tool_f1: 94.92%
tool_exact_match_rate: 81.25%
tool_invocation_rate: 100.00%
tool_execution_success_rate: 96.83%
conditional_execution_rate: 93.75%
evidence_recall_at_5: 100.00%
irrelevant_retrieval_rate_at_5: 57.50%
judge_success_rate: 100.00%
judge_cost_coverage_rate: 100.00%
structured_output_repair_rate: 12.50%
Average latency: 6008.98 ms
Input tokens: 173182
Output tokens: 11412
Reasoning tokens: 0
Retries: 0
Structured-output repairs: 2
Infrastructure failures: 0
Estimated cost: $0.01312980
Judge llm answer correctness grade: 2.94/5
Judge workflow correctness: 3.06/5
Judge chronological coherence: 4.00/5
Judge workflow efficiency: 3.88/5
Judge auditability: 4.06/5
Judge model invocations: 16
Judge input tokens: 51079
Judge output tokens: 26359
Judge reasoning tokens: 0
Judge retries: 0
Judge estimated cost: $0.2011614

### AMZN findings and conclusion

In this Nova Lite batch, execution and grounding were reliable: all 16 runs completed, evidence validity, evidence completeness, and Evidence Recall@5 were 100%, and Tool F1 was 94.92%. Retrieval still contained noise (57.50% irrelevant-retrieval rate), but the required evidence was consistently available.

Numerical correctness was 37.50%, while formula and audit-trail correctness were 33.33% and 37.50%. The model answered the normalized direct-fact questions and all four single-formula questions correctly. The review table contains ten questions; all had complete evidence, so their failures came after retrieval.

Every AMZN review row explained:

- **AMZN-03 — fails numerical, formatting, and audit:** the cited filing tables report values in millions, but the structured answer stored `45606 USD` and the text said `$45,606 million`. The required absolute value is `45606000000 USD`.
- **AMZN-04 — fails numerical, formatting, and audit:** the same scaling error produced `4750 USD`/`$4,750 million` instead of the required `4750000000 USD`.
- **AMZN-09 — fails numerical, formula, and audit:** `percentage(old, new)` returned old/new ratios rather than growth. The answer gave 88.99% and 15.77%; gold requires 12.38% net-sales growth and 16.59% operating-income growth.
- **AMZN-10 — fails numerical, formula, and audit:** the model again calculated old/new ratios, reporting 76.28% and 83.06% instead of growth rates of 31.09% and 20.40%; it therefore also chose the wrong faster-growing measure.
- **AMZN-11 — fails numerical, formula, and audit:** the absolute change used FY2024 minus FY2023, returning `$97,040,000,000` instead of FY2025 minus FY2024, `$193,148,000,000`. Its final 30.91% was not reproduced by the recorded calculator event, which returned the new/old ratio 130.91%.
- **AMZN-12 — fails numerical, formula, formatting, and audit:** the model used the wrong AWS periods and treated new/old ratios as growth. The structured AWS value was 18.63% while the prose said 11.9%; gold requires 14.49%. The prose and structured values also disagreed.
- **AMZN-13 — fails numerical, formula, formatting, and audit:** the question requires four annual margins—10.75%, 11.16%, 9.29%, and 10.83%—but the answer returned only decimal changes, `0.0040%` and `0.0155%`, and did not display the required values.
- **AMZN-14 — fails numerical, formula, and audit:** the answer returned only a 3.39% change and said the share increased. Gold requires the two annual shares, 58.07% and 57.03%, which show a decline.
- **AMZN-15 — fails numerical, formula, and audit:** after summing the three cash-flow values correctly, the model divided FY2025 cash flow alone by three. It returned only 178.48%; gold requires the `$113,445,666,666.67` average, `$26,068,333,333.33` difference, and 22.98%.
- **AMZN-16 — fails numerical, formula, formatting, and audit:** the response mixed old/new ratios with growth and missed strict two-decimal targets: 88.99%, 16.59%, 20.41%, and 30.92% were returned instead of 12.38%, 16.59%, 20.40%, and 30.91%. The prose stated only a conclusion and did not display the structured values.

The main AMZN bottleneck was therefore financial calculation and unit handling, not access to evidence. The separate judge cost was $0.2012, compared with $0.0131 for the Nova answer batch.

## Save evaluation files

The run records were saved before evaluation. Add the computed metric and judge files to that same result folder.

In [36]:
results_dir = save_evaluation_results(
    results_dir, question_metrics, summary, retrieval_metrics,
    judge_rows=judge_metrics or None,
)
results_dir

PosixPath('/home/atanas-vitanov/Documents/final_project_financial_agent/results/2026-08-31T151912559431Z-monolithic-amazon-nova-lite-v1-0-AMZN')

In [37]:
DataFrame({"saved_file": sorted(path.name for path in results_dir.iterdir())})

              saved_file
0    judge_records.jsonl
1   question_metrics.csv
2  retrieval_metrics.csv
3             runs.jsonl
4           summary.json

## Failures

Provider and tool failures remain experimental results. They are displayed rather than silently rerun or repaired.

In [38]:
DataFrame(
    [
        {"question_id": run.question.question_id,
         "failure_category": run.failure_category,
         "failure_message": run.failure_message}
        for run in batch_runs if run.status == "failure"
    ],
    columns=("question_id", "failure_category", "failure_message"),
)

Empty DataFrame
Columns: [question_id, failure_category, failure_message]
Index: []

# Validation batch: Alphabet (GOOGL)

Run the frozen validation company after reviewing the AMZN development results.

In [39]:
validation_ticker = "GOOGL"
validation_gold_records = load_gold_questions(validation_ticker)
validation_gold_by_id = {
    record["question_id"]: record for record in validation_gold_records
}

In [40]:
validation_runs = harness.run_batch(validation_ticker)
assert len(validation_runs) == len(validation_gold_records)
validation_results_dir = save_run_records(validation_runs)

In [41]:
DataFrame([
    {"question_id": run.question.question_id, "status": run.status}
    for run in validation_runs
])

   question_id   status
0     googl-01  success
1     googl-02  success
2     googl-03  success
3     googl-04  success
4     googl-05  success
5     googl-06  success
6     googl-07  success
7     googl-08  success
8     googl-09  success
9     googl-10  success
10    googl-11  success
11    googl-12  success
12    googl-13  success
13    googl-14  success
14    googl-15  success
15    googl-16  success

## Inspect every answer

Use the same compact answer and gold comparison as the AMZN batch.

In [42]:
for run in validation_runs:
    gold = validation_gold_by_id[run.question.question_id]["answer"]
    print(format_run_summary(run, gold))
    print("-" * 88)

Question: What were Alphabet Inc.'s consolidated revenues in fiscal 2025?
Model answer: Alphabet Inc.'s consolidated revenues in fiscal 2025 were $402,836 million.
Gold answer: 402836000000
Gold values: -
Tools: search_filing (ok)
Evidence: filing-googl-2025-page-0033-table-02
Latency: 3668.83 ms | Tokens: {'inputTokens': 7706, 'outputTokens': 337, 'totalTokens': 8043} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00046236', 'output': '0.00008088', 'total': '0.00054324'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/f5cfc74df3745a7e81adbe33a9dc837b
----------------------------------------------------------------------------------------
Question: What was Alphabet Inc.'s consolidated income from operations in fiscal 2025?
Model answer: Alphabet Inc.'s consolidated income from operations in fiscal 2025 was $129,039,000,000.
Gold answer: 129039000000
Gold values: -
Tools: lookup_fact (ok)
Evidence: fact-googl-operating-income-fy2025
Latency: 2367.48 ms | Tokens: {'inputTokens': 3983, 'outputTokens': 273, 'totalTokens': 4256} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00023898', 'output': '0.00006552', 'total': '0.00030450'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/1ef75863dede42b758091ea97fe5451f
----------------------------------------------------------------------------------------
Question: Which Alphabet reportable segment generated the most operating income in fiscal 2025, and how much did it generate?
Model answer: Google Services generated the most operating income in fiscal 2025 with $139,404 million.
Gold answer: 139404000000
Gold values: -
Tools: search_filing (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: filing-googl-2025-page-0037-table-02, filing-googl-2025-page-0088-table-02
Latency: 8934.03 ms | Tokens: {'inputTokens': 35670, 'outputTokens': 801, 'totalTokens': 36471} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0021402', 'output': '0.00019224', 'total': '0.00233244'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/786f394ffbeba3b590597d7f5b20a46f
----------------------------------------------------------------------------------------
Question: What was Google Cloud's operating income in fiscal 2025?
Model answer: Google Cloud's operating income in fiscal 2025 was $13,910 million.
Gold answer: 13910000000
Gold values: -
Tools: search_filing (ok)
Evidence: filing-googl-2025-page-0037-table-02, filing-googl-2025-page-0088-table-02
Latency: 5621.0 ms | Tokens: {'inputTokens': 14449, 'outputTokens': 561, 'totalTokens': 15010} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00086694', 'output': '0.00013464', 'total': '0.00100158'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/fbca8d1dd6f9614dce37e70563f745fc
----------------------------------------------------------------------------------------
Question: What was Alphabet Inc.'s operating margin in fiscal 2025?
Model answer: Alphabet Inc.'s operating margin in fiscal 2025 was 32.03 percent.
Gold answer: 32.03
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-googl-operating-income-fy2025, fact-googl-revenue-fy2025
Latency: 4053.79 ms | Tokens: {'inputTokens': 6794, 'outputTokens': 423, 'totalTokens': 7217} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00040764', 'output': '0.00010152', 'total': '0.00050916'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/ab306d4b7171e14d36661798108b91b3
----------------------------------------------------------------------------------------
Question: What was Alphabet Inc.'s net profit margin in fiscal 2025?
Model answer: Alphabet Inc.'s net profit margin in fiscal 2025 was 32.81%. The net income was $132,170 million and the revenue was $402,836 million.
Gold answer: 32.81
Gold values: -
Tools: search_filing (ok), search_filing (ok), calculate (ok)
Evidence: filing-googl-2025-page-0051-table-02, filing-googl-2025-page-0034-table-02
Latency: 5015.68 ms | Tokens: {'inputTokens': 22935, 'outputTokens': 491, 'totalTokens': 23426} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0013761', 'output': '0.00011784', 'total': '0.00149394'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/6c8860f25edd07d483d3994e108b2d66
----------------------------------------------------------------------------------------
Question: What share of Alphabet Inc.'s fiscal 2025 revenues was represented by operating cash flow?
Model answer: The share of Alphabet Inc.'s fiscal 2025 revenues represented by operating cash flow was 40.89%.
Gold answer: 40.89
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-googl-operating-cash-flow-fy2025, fact-googl-revenue-fy2025
Latency: 4271.9 ms | Tokens: {'inputTokens': 6855, 'outputTokens': 462, 'totalTokens': 7317} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0004113', 'output': '0.00011088', 'total': '0.00052218'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/7b0f102468a418c5e79d6c07f34fd4ac
----------------------------------------------------------------------------------------
Question: What was Alphabet Inc.'s operating cash flow as a percentage of net income in fiscal 2025?
Model answer: Alphabet Inc.'s operating cash flow as a percentage of net income in fiscal 2025 was 124.62%
Gold answer: 124.62
Gold values: -
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok)
Evidence: fact-googl-operating-cash-flow-fy2025, fact-googl-net-income-fy2025
Latency: 4104.2 ms | Tokens: {'inputTokens': 6883, 'outputTokens': 466, 'totalTokens': 7349} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041298', 'output': '0.00011184', 'total': '0.00052482'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/243d19eb8142a2bab4a01d65a0731ad8
----------------------------------------------------------------------------------------
Question: Between fiscal 2024 and fiscal 2025, how did Alphabet's revenue growth compare with its operating income growth?
Model answer: Between fiscal 2024 and fiscal 2025, Alphabet's operating income grew faster than its revenue.
Gold answer: revenues grew faster than operating income; the growth-rate difference was 0.28 percentage points
Gold values: revenue growth: 15.09 percent, operating income growth: 14.81 percent
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-revenue-fy2024, fact-googl-revenue-fy2025, fact-googl-operating-income-fy2024, fact-googl-operating-income-fy2025
Latency: 5689.96 ms | Tokens: {'inputTokens': 6962, 'outputTokens': 694, 'totalTokens': 7656} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00041772', 'output': '0.00016656', 'total': '0.00058428'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/de3ca88915b25f3705348af973ba95c5
----------------------------------------------------------------------------------------
Question: How did Alphabet's net income growth compare with its operating cash flow growth from fiscal 2024 to fiscal 2025?
Model answer: Alphabet's net income growth from fiscal 2024 to fiscal 2025 was 75.75%, while its operating cash flow growth was 76.07%. Operating cash flow grew at a slightly higher rate than net income.
Gold answer: net income grew faster than operating cash flow; the growth-rate difference was 0.56 percentage points
Gold values: net income growth: 32.01 percent, operating cash flow growth: 31.46 percent
Tools: lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-net-income-fy2024, fact-googl-net-income-fy2025, fact-googl-operating-cash-flow-fy2024, fact-googl-operating-cash-flow-fy2025
Latency: 5903.21 ms | Tokens: {'inputTokens': 7026, 'outputTokens': 730, 'totalTokens': 7756} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00042156', 'output': '0.0001752', 'total': '0.00059676'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/7c18c0791078eb3becf53053cd320816
----------------------------------------------------------------------------------------
Question: How did Alphabet Inc.'s total assets change from fiscal 2024 to fiscal 2025 in dollar and percentage terms?
Model answer: Alphabet Inc.'s total assets increased by $145,025,000,000 from fiscal 2024 to fiscal 2025, representing a 32.21% increase.
Gold answer: total assets increased
Gold values: absolute change: 145025000000 USD, percentage change: 32.21 percent
Tools: lookup_fact (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-total-assets-fy2024, fact-googl-total-assets-fy2025
Latency: 6164.5 ms | Tokens: {'inputTokens': 6302, 'outputTokens': 672, 'totalTokens': 6974} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00037812', 'output': '0.00016128', 'total': '0.00053940'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/f51b2a57b4394e4fda77da3411617085
----------------------------------------------------------------------------------------
Question: From fiscal 2024 to fiscal 2025, how did Google Services operating income growth compare with Alphabet's consolidated operating income growth?
Model answer: Google Services operating income grew by 86.99% from fiscal 2024 to fiscal 2025, while Alphabet's consolidated operating income grew by 87.10% over the same period.
Gold answer: Google Services operating income grew faster than consolidated operating income; the growth-rate difference was 0.15 percentage points
Gold values: Google Services operating income growth: 14.96 percent, consolidated operating income growth: 14.81 percent
Tools: search_filing (ok), search_filing (ok), calculate (ok), calculate (ok)
Evidence: filing-googl-2025-page-0037-table-02
Latency: 6407.6 ms | Tokens: {'inputTokens': 23519, 'outputTokens': 641, 'totalTokens': 24160} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00141114', 'output': '0.00015384', 'total': '0.00156498'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/d05930567f86aa363a14398ebf5ca56f
----------------------------------------------------------------------------------------
Question: Between fiscal 2024 and fiscal 2025, how did Alphabet's operating margin and net profit margin develop, and which changed more?
Model answer: Between fiscal 2024 and fiscal 2025, Alphabet's net profit margin changed more than its operating margin.
Gold answer: operating margin declined by 0.08 percentage points; net profit margin increased by 4.21 percentage points; net profit margin changed more
Gold values: 2024 operating margin: 32.11 percent, 2025 operating margin: 32.03 percent, 2024 net profit margin: 28.60 percent, 2025 net profit margin: 32.81 percent
Tools: lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-operating-income-fy2024, fact-googl-operating-income-fy2025, fact-googl-revenue-fy2024, fact-googl-revenue-fy2025, fact-googl-net-income-fy2024, fact-googl-net-income-fy2025
Latency: 15021.13 ms | Tokens: {'inputTokens': 15429, 'outputTokens': 2101, 'totalTokens': 17530} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.00092574', 'output': '0.00050424', 'total': '0.00142998'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/e1ac9acd6fd1564e0a1b5524dacaedfc
----------------------------------------------------------------------------------------
Question: How did Google Services' share of Alphabet's consolidated operating income change from fiscal 2024 to fiscal 2025?
Model answer: The share of Alphabet's consolidated operating income for Google Services increased by 86.99% from fiscal 2024 to fiscal 2025.
Gold answer: Google Services' share of consolidated operating income increased by 0.14 percentage points
Gold values: 2024 Google Services share of consolidated operating income: 107.89 percent, 2025 Google Services share of consolidated operating income: 108.03 percent
Tools: search_filing (ok), calculate (failed), calculate (failed), calculate (ok)
Evidence: filing-googl-2025-page-0088-table-02, filing-googl-2025-page-0037-table-02
Latency: 8280.41 ms | Tokens: {'inputTokens': 27393, 'outputTokens': 758, 'totalTokens': 28151} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.00164358', 'output': '0.00018192', 'total': '0.00182550'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/a91f99311a8d715bdfa48ea7784921ab
----------------------------------------------------------------------------------------
Question: How did Alphabet's fiscal 2025 operating cash flow compare with its average annual operating cash flow for fiscal 2023 through fiscal 2025?
Model answer: Alphabet's fiscal 2025 operating cash flow was 230.27% higher than its average annual operating cash flow for fiscal 2023 through fiscal 2025.
Gold answer: fiscal 2025 operating cash flow was 26.13 percent above the three-year average
Gold values: three-year average operating cash flow: 130586000000.00 USD, 2025 difference from average: 34127000000.00 USD, 2025 percentage difference from average: 26.13 percent
Tools: lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-operating-cash-flow-fy2023, fact-googl-operating-cash-flow-fy2024, fact-googl-operating-cash-flow-fy2025
Latency: 6894.22 ms | Tokens: {'inputTokens': 9255, 'outputTokens': 858, 'totalTokens': 10113} | Retries: 0
Structured-output repairs: 0
Cost: {'input': '0.0005553', 'output': '0.00020592', 'total': '0.00076122'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/d3cc0459b2abd66afe7178b725129ec8
----------------------------------------------------------------------------------------
Question: Did Alphabet's revenues, operating income, operating cash flow, and total assets grow at similar rates from fiscal 2024 to fiscal 2025?
Model answer: Alphabet's revenues, operating income, operating cash flow, and total assets did not grow at similar rates from fiscal 2024 to fiscal 2025.
Gold answer: all four measures increased; total assets grew fastest; operating income grew slowest; the spread between the fastest and slowest growth rates was 17.40 percentage points
Gold values: revenue growth: 15.09 percent, operating income growth: 14.81 percent, operating cash flow growth: 31.46 percent, total assets growth: 32.21 percent
Tools: lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), lookup_fact (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok), calculate (ok)
Evidence: fact-googl-revenue-fy2024, fact-googl-revenue-fy2025, fact-googl-operating-income-fy2024, fact-googl-operating-income-fy2025, fact-googl-operating-cash-flow-fy2024, fact-googl-operating-cash-flow-fy2025, fact-googl-total-assets-fy2024, fact-googl-total-assets-fy2025
Latency: 13920.76 ms | Tokens: {'inputTokens': 12522, 'outputTokens': 2035, 'totalTokens': 14557} | Retries: 0
Structured-output repairs: 1
Cost: {'input': '0.00075132', 'output': '0.0004884', 'total': '0.00123972'}
Trace: https://cloud.langfuse.com/project/cmrva8h6h0hchad0d3guy659p/traces/1c41045e39c59b4388b85cb62daf7882
----------------------------------------------------------------------------------------

## Deterministic evaluation

In [43]:
validation_saved_evaluation = evaluate_saved_results(
    latest=True, architecture=validation_runs[0].architecture,
    ticker=validation_ticker,
)
assert validation_saved_evaluation["results_directory"] == validation_results_dir
validation_question_metrics = validation_saved_evaluation["question_rows"]
validation_retrieval_metrics = validation_saved_evaluation["retrieval_rows"]
validation_summary = validation_saved_evaluation["summary"]

## Exploratory Haiku 4.5 workflow review

These qualitative scores support diagnosis only. They cannot override deterministic numerical or audit failures.

In [44]:
validation_saved_evaluation = evaluate_saved_results(
    latest=True, rerun_judge=True,
    architecture=validation_runs[0].architecture, ticker=validation_ticker,
)
assert validation_saved_evaluation["results_directory"] == validation_results_dir
validation_judge_metrics = validation_saved_evaluation["judge_rows"] or []
validation_summary = validation_saved_evaluation["summary"]

In [45]:
DataFrame(validation_judge_metrics, columns=(
    "question_id", "llm_answer_correctness_grade", "workflow_correctness",
    "chronological_coherence", "workflow_efficiency", "auditability",
))

,question_id,llm_answer_correctness_grade,workflow_correctness,chronological_coherence,workflow_efficiency,auditability
0,googl-01,2,2,5,5,3
1,googl-02,5,5,5,4,5
2,googl-03,3,2,5,2,2
3,googl-04,3,3,5,5,3
4,googl-05,5,5,5,5,5
5,googl-06,5,5,5,5,4
6,googl-07,5,5,5,5,5
7,googl-08,5,5,5,5,5
8,googl-09,1,1,2,3,4
9,googl-10,1,1,5,4,5
10,googl-11,4,3,5,5,3
11,googl-12,1,1,3,2,2
12,googl-13,1,2,5,4,5
13,googl-14,1,1,2,3,2
14,googl-15,1,1,2,1,2
15,googl-16,1,1,5,4,4

### GOOGL questions needing review

Only GOOGL runs with a failed deterministic check appear in this table.

In [46]:
validation_failed_question_metrics = [
    row for row in validation_question_metrics if row["status"] != "success"
    or any(row[name] is not True for name in CHECKS)
]
DataFrame(validation_failed_question_metrics, columns=(
    "question_id", "category", "numerical_correct",
    "evidence_complete", "formula_correct", "formatting_correct",
    "audit_trail_complete",
))

,question_id,category,numerical_correct,evidence_complete,formula_correct,formatting_correct,audit_trail_complete
0,googl-01,direct_extraction,False,True,None,False,False
1,googl-03,direct_extraction,False,True,None,False,False
2,googl-04,direct_extraction,False,True,None,False,False
3,googl-06,single_formula,True,True,False,False,False
4,googl-09,period_comparison,False,True,False,False,False
5,googl-10,period_comparison,False,True,False,True,False
6,googl-11,period_comparison,True,True,False,True,False
7,googl-12,period_comparison,False,True,False,True,False
8,googl-13,multi_step,False,True,False,False,False
9,googl-14,multi_step,False,True,False,True,False
10,googl-15,multi_step,False,True,False,True,False
11,googl-16,multi_step,False,True,False,False,False

### Metrics by question type

In [47]:
DataFrame(validation_summary["by_category"]).T.rename_axis("question_type")

,run_count,numerical_correctness_rate,evidence_completeness_rate,formula_correctness_rate,formatting_correctness_rate
question_type,,,,,
direct_extraction,4.0,0.25,1.0,NaN,0.25
multi_step,4.0,0.00,1.0,0.00,0.50
period_comparison,4.0,0.25,1.0,0.00,0.75
single_formula,4.0,1.00,1.0,0.75,0.75

### Final metrics

In [48]:
print(format_evaluation_summary(validation_summary))

Runs: 16
run_success_rate: 100.00%
numerical_correctness_rate: 37.50%
evidence_validity_rate: 100.00%
evidence_completeness_rate: 100.00%
formula_correctness_rate: 25.00%
formatting_correctness_rate: 56.25%
unsupported_number_rate: 20.83%
audit_trail_completeness_rate: 25.00%
math_repair_invocation_rate: 0.00%
math_repair_success_rate: 0.00%
tool_precision: 89.66%
tool_recall: 86.67%
tool_f1: 88.14%
tool_exact_match_rate: 68.75%
tool_invocation_rate: 100.00%
tool_execution_success_rate: 96.88%
conditional_execution_rate: 85.42%
evidence_recall_at_5: 100.00%
irrelevant_retrieval_rate_at_5: 32.50%
judge_success_rate: 100.00%
judge_cost_coverage_rate: 100.00%
structured_output_repair_rate: 12.50%
Average latency: 6644.92 ms
Input tokens: 213683
Output tokens: 12303
Reasoning tokens: 0
Retries: 0
Structured-output repairs: 2
Infrastructure failures: 0
Estimated cost: $0.01577370
Judge llm answer correctness grade: 2.75/5
Judge workflow correctness: 2.69/5
Judge chronological coherence: 4.31/5
Judge workflow efficiency: 3.88/5
Judge auditability: 3.69/5
Judge model invocations: 16
Judge input tokens: 50653
Judge output tokens: 27343
Judge reasoning tokens: 0
Judge retries: 0
Judge estimated cost: $0.2061048

### GOOGL findings and conclusion

In this Nova Lite validation batch, all 16 runs completed, evidence validity, evidence completeness, and Evidence Recall@5 were 100%, and Tool F1 was 88.14%. Retrieval was less noisy than for AMZN, with a 32.50% irrelevant-retrieval rate, although tool selection and execution were slightly weaker.

Numerical correctness was 37.50%, and formula and audit-trail correctness were both 25.00%. The review table contains twelve questions. Evidence completeness passed for every row; two rows have numerically correct final answers but remain here because their formula or audit trail failed.

Every GOOGL review row explained:

- **GOOGL-01 — fails numerical, formatting, and audit:** a filing value expressed in millions was stored as `402836 USD` and displayed as `$402,836 million`; gold requires `402836000000 USD`.
- **GOOGL-03 — fails numerical, formatting, and audit:** the correct Google Services tables were cited, but `139404 USD` was stored instead of `139404000000 USD`. Several unnecessary subtraction calls did not fix the scale.
- **GOOGL-04 — fails numerical, formatting, and audit:** `13910 USD`/`$13,910 million` was returned instead of the absolute value `13910000000 USD`.
- **GOOGL-06 — numerical passes; formula, formatting, and audit fail:** the final 32.81% margin is correct, but the trace contains only `divide(132170, 402836) = 0.328...`, not the expected percentage operation. The prose also introduces `$132,170 million` and `$402,836 million`, violating the absolute-number display rule.
- **GOOGL-09 — fails numerical, formula, formatting, and audit:** 32.11% is an operating margin, not revenue growth, and 114.81% is a new/old ratio. Gold requires 15.09% revenue growth and 14.81% operating-income growth; the prose omits those numbers.
- **GOOGL-10 — fails numerical, formula, and audit:** old/new ratios of 75.75% and 76.07% were reported instead of net-income and cash-flow growth of 32.01% and 31.46%, reversing the comparison.
- **GOOGL-11 — numerical and formatting pass; formula and audit fail:** the final `$145,025,000,000` and 32.21% are correct, but the calculator returned 132.21% and no recorded subtraction converted that ratio to growth. The correct final percentage is therefore unsupported by the trace.
- **GOOGL-12 — fails numerical, formula, and audit:** the model returned old/new ratios of 86.99% and 87.10% instead of growth rates of 14.96% and 14.81%.
- **GOOGL-13 — fails numerical, formula, formatting, and audit:** it returned only decimal changes, `0.0033%` and `-0.0421%`, rather than the four required annual margins. The signs and percent scaling were also wrong, and the required values were absent from the prose.
- **GOOGL-14 — fails numerical, formula, and audit:** the answer supplied only an 86.99% old/new ratio. Gold requires annual Google Services shares of 107.89% and 108.03%; neither was returned.
- **GOOGL-15 — fails numerical, formula, and audit:** the correct three-year sum was `391758000000`, but the next calculation divided an unrelated `149616000000` by three. It returned only 230.27%; gold requires a `$130,586,000,000.00` average, `$34,127,000,000.00` difference, and 26.13%.
- **GOOGL-16 — fails numerical, formula, formatting, and audit:** all four outputs were old/new ratios—86.89%, 87.10%, 81.20%, and 75.64%—rather than growth rates of 15.09%, 14.81%, 31.46%, and 32.21%. The prose again omitted the structured values.

The judge again rated auditability (3.69/5) above answer correctness (2.75/5). The traces were inspectable, but Nova Lite was not consistently precise enough for period comparisons and multi-step financial reasoning. Judge cost was $0.2061 versus $0.0158 for the Nova answer batch.

## Save evaluation files

In [49]:
validation_results_dir = save_evaluation_results(
    validation_results_dir, validation_question_metrics, validation_summary,
    validation_retrieval_metrics, judge_rows=validation_judge_metrics,
)
validation_results_dir

PosixPath('/home/atanas-vitanov/Documents/final_project_financial_agent/results/2026-08-31T152441084692Z-monolithic-amazon-nova-lite-v1-0-GOOGL')

In [50]:
DataFrame({"saved_file": sorted(path.name for path in validation_results_dir.iterdir())})

              saved_file
0    judge_records.jsonl
1   question_metrics.csv
2  retrieval_metrics.csv
3             runs.jsonl
4           summary.json

## Failures

In [51]:
DataFrame(
    [
        {"question_id": run.question.question_id,
         "failure_category": run.failure_category,
         "failure_message": run.failure_message}
        for run in validation_runs if run.status == "failure"
    ],
    columns=("question_id", "failure_category", "failure_message"),
)

Empty DataFrame
Columns: [question_id, failure_category, failure_message]
Index: []

## Overall Nova Lite conclusion

Across AMZN and GOOGL, the monolithic Nova Lite agent's main weakness was not evidence access: every run completed, evidence completeness and Evidence Recall@5 were 100%, and the saved traces usually showed the correct source facts. The dominant problem was applying financial meaning after retrieval.

The most frequent errors were failing to convert filing values reported in millions into absolute USD, treating old/new or new/old ratios as growth rates, selecting the wrong fiscal-period operands, and returning only one comparison value when the question required several intermediate and final values. Some answers were numerically correct but still failed formula or audit checks because the recorded calculator calls did not reproduce the final number. Formatting failures mostly came from magnitude words such as `million` or from prose that omitted or contradicted the structured values.

Performance therefore declined as reasoning depth increased: normalized direct facts and single-formula questions were strongest, while period comparisons and multi-step questions produced most errors. For this model, the primary reliability risk is calculation semantics and multi-step completeness, followed by unit scaling—not hallucinated evidence.